---

- name: Ensure matrix-appservice-polychat paths exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - {path: "{{ matrix_appservice_polychat_base_path }}", when: true}
    - {path: "{{ matrix_appservice_polychat_config_path }}", when: true}
    - {path: "{{ matrix_appservice_polychat_data_path }}", when: true}
    - {path: "{{ matrix_appservice_polychat_docker_src_files_path }}", when: "{{ matrix_appservice_polychat_container_image_self_build }}"}
  when: "item.when | bool"

- name: Ensure matrix-appservice-polychat container image is pulled
  community.docker.docker_image:
    name: "{{ matrix_appservice_polychat_docker_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ matrix_appservice_polychat_docker_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_appservice_polychat_docker_image_force_pull }}"
  when: "not matrix_appservice_polychat_container_image_self_build | bool"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- when: "matrix_appservice_polychat_container_image_self_build | bool"
  block:
    - name: Ensure matrix-appservice-polychat repository is present on self-build
      ansible.builtin.git:
        repo: "{{ matrix_appservice_polychat_container_image_self_build_repo }}"
        dest: "{{ matrix_appservice_polychat_docker_src_files_path }}"
        version: "{{ matrix_appservice_polychat_container_image_self_build_repo_version }}"
        force: "yes"
      become: true
      become_user: "{{ matrix_user_username }}"
      register: matrix_appservice_polychat_git_pull_results

    - name: Ensure matrix-appservice-polychat container image is built
      community.docker.docker_image:
        name: "{{ matrix_appservice_polychat_docker_image }}"
        source: build
        force_source: "{{ matrix_appservice_polychat_git_pull_results.changed if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else matrix_appservice_polychat_git_pull_results.changed }}"
        build:
          dockerfile: "{{ matrix_appservice_polychat_container_image_self_build_repo_dockerfile_path }}"
          path: "{{ matrix_appservice_polychat_docker_src_files_path }}"
          pull: true

- name: Ensure matrix-appservice-polychat config is installed
  ansible.builtin.copy:
    content: "{{ matrix_appservice_polychat_configuration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ matrix_appservice_polychat_config_path }}/config.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure matrix-appservice-polychat schema.yml template exists
  ansible.builtin.template:
    src: "{{ role_path }}/templates/schema.yml.j2"
    dest: "{{ matrix_appservice_polychat_config_path }}/schema.yml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure matrix-appservice-polychat database.json template exists
  ansible.builtin.template:
    src: "{{ role_path }}/templates/database.json.j2"
    dest: "{{ matrix_appservice_polychat_data_path }}/database.json"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure appservice-polychat registration.yaml installed
  ansible.builtin.copy:
    content: "{{ matrix_appservice_polychat_registration | to_nice_yaml(indent=2, width=999999) }}"
    dest: "{{ matrix_appservice_polychat_config_path }}/polychat-registration.yaml"
    mode: 0644
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"

- name: Ensure matrix-appservice-polychat container network is created
  community.general.docker_network:
    name: "{{ matrix_appservice_polychat_container_network }}"
    driver: bridge

- name: Ensure matrix-appservice-polychat support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ matrix_appservice_polychat_base_path }}/{{ item }}"
    mode: 0640
    owner: "{{ matrix_user_username }}"
    group: "{{ matrix_user_groupname }}"
  with_items:
    - labels

- name: Ensure matrix-appservice-polychat.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/matrix-appservice-polychat.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/matrix-appservice-polychat.service"
    mode: 0644
